apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: contacts-app-ui
  name: contacts-app-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contacts-app-ui
  template:
    metadata:
      labels:
        app: contacts-app-ui
    spec:
      containers:
      - image: felipeg48/contacts-app-ui:v1.0
        name: contacts-app-ui
        env:
          - name: CONTACTS_SERVER
            value: http://contacts-app/contacts
          - name: CONTACTS_USERNAME
            value: admin
          - name: CONTACTS_PASSWORD
            value: admin
          - name: SERVER_PORT
            value: "8080"
        resources:
          requests:
            memory: "732Mi"
            cpu: "500m"
          limits:
            memory: "732Mi"
            cpu: "500m"

