apiVersion: v1
kind: Service
metadata:
  labels:
    app: contacts-app-ui
  name: contacts-app-ui
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: contacts-app-ui
  type: LoadBalancer
